[[transform]]
name = "license"
delimiters = ["/* license:start */", "/* license:end */"]
effects = [{ replace = "// SPDX-License-Identifier: Apache-2.0" }]

[[transform]]
name = "todo"
delimiters = [{ regex = '/\*todo:([^*]+)\*/' }, "/*end*/"]
effects = [{ replace = 'panic!("TODO: {0}");' }, { log = true }]

[[transaction]]
src = "src"
dst = "../prod/src"
log = "../prod/todos.jsonl"
pattern = ["**/*.rs"]
transform = ["license", "todo"]

[[transaction]]
src = "README.md"
dst = "../prod/README.md"
transform = []
