[[transform]]
name = "anchor"
delimiters = [{ regex = '# anchor:([a-z-]+)' }]
effects = [{ log = true }]

[[transaction]]
src = "config"
log = "../prod/anchors.jsonl"
pattern = ["**/*.toml"]
transform = ["anchor"]
