[[transform]]
name = "blank"
delimiters = ["/*blank*/", "/*end*/"]
action = { replace = "" }

[[transform]]
name = "todo"
delimiters = [{ regex = '/\*todo:(([^*]|\*[^/])*)\*/' }, "/*end*/"]
action = { replace = 'todo!("$1")' }

[[transaction]]
src = "build.rs"
dst = "../prod/build.rs"
transform = ["blank"]

[[transaction]]
src = "src"
dst = "../prod/src"
pattern = ["**"]
transform = ["blank", "todo"]

[[post]]
system = { dir = "../prod", cmd = "cargo fmt" }
