[[transform]]
name = "blank"
delimiters = ["/*blank*/", "/*end*/"]
# replace everything inclusively between delimiters with empty string
action = { replace = "" }

[[transform]]
name = "todo"
# supports capturing groups
delimiters = [{ regex = '/\*todo:(([^*]|\*[^/])*)\*/' }, "/*end*/"]
# use {0} to refer to the capturing group at 0-based index
# to type curly braces, use double curly braces
action = { replace = 'todo!("{0}")' }

[[transform]]
name = "todo-block"
delimiters = [{ regex = '/\*todo:(([^*]|\*[^/])*)\*/' }, "/*end*/"]
action = { log = "block" }

[[transform]]
name = "anchor"
delimiters = ["/*anchor*/"]
action = { log = "anchor" }

[[transaction]]
src = "build.rs"
dst = "../prod/build.rs"
transform = ["blank"]

[[transaction]]
src = "src"
dst = "../prod/src"
log = "../prod/mosaika.log"
pattern = ["**/*"]
transform = ["blank", "todo", "anchor"]

[[transaction]]
src = "src"
log = "../prod/mosaika-find.log"
pattern = ["**/*"]
transform = ["todo-block", "anchor"]

[[post]]
system = { dir = "../prod", cmd = "rustfmt build.rs src/main.rs" }
